  `services:`
    `springboot-app:`
    `build: .`
    `ports:`
    `- "8085:8085"`
    `depends_on:`
    `- mysql-db`
    `environment:`
    `SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/mydb`
    `SPRING_DATASOURCE_USERNAME: root`
    `SPRING_DATASOURCE_PASSWORD: root`

    `mysql-db:`
    `image: mysql:8.0`
    `environment:`
    `MYSQL_ROOT_PASSWORD: root`
    `MYSQL_DATABASE: mydb`
    `ports:`
    `- "3306:3306"`
    `volumes:`
    `- mysql_data:/var/lib/mysql`

    `volumes:`
    `mysql_data:`